<MyRoot>:

    inputImage: inputImage

    BoxLayout:
        orientation: "vertical"

        Label:
            text: "ImgSuite"
            font_size: 64
            color: 0.0078, 0.6, 0.34

        Image:
            id: inputImage
            source: ""
            size: self.texture_size

        Button:
            text: "Load"
            font_size: 32
            size: 100, 50
            on_press: root.loadImage()
